Set time window via environment variables (#27)

diff --git a/rootfs/etc/services.d/speedtest/run b/rootfs/etc/services.d/speedtest/run
--- a/rootfs/etc/services.d/speedtest/run
+++ b/rootfs/etc/services.d/speedtest/run
@@ -2,6 +2,18 @@
 
 # this script is invoced every 6 minutes if clipboard is set to 'RUN', then a speedtest runs
 
+time_to_minutes() {
+    local TIME="$1"
+    IFS=':' read -r HOUR MINUTE <<< "$TIME"
+    if ! [[ "$HOUR" =~ ^[0-9]+$ && "$MINUTE" =~ ^[0-9]+$ ]]; then
+        echo "Invalid time format. Use HH:MM or H:MM" >&2
+        return 1
+    fi
+    echo $(( $HOUR*60 + $MINUTE ))
+}
+
+start_time_minutes=$(time_to_minutes $TIME_START)
+end_time_minutes=$(time_to_minutes $TIME_END)
 
 while true
 do
@@ -21,32 +33,25 @@ do
         # Get the current hour and minute in 24-hour format (e.g., 14:30)
         current_time=$(date +"%H:%M:%S")
         echo "Current time is $current_time"
-        
-        
+
+
         # Save the hour and minute
         current_hour=$(date +"%H")
         current_minute=$(date +"%M")
         current_hour=${current_hour#0}
         current_minute=${current_minute#0}
 
-        # Convert the start and end times to minutes for easier comparison
-        # 13:00 in minutes
-        start_time_minutes=$(( 13 * 60 ))
-        # 22:30 in minutes
-        end_time_minutes=$(( 22 * 60 + 30 ))
-
-
         # Convert the current time to minutes for comparison
         let "current_time_minutes=$current_hour * 60 + $current_minute"
 
-        
+
         # Check if the current time is within the specified range
         # --> only start speedtesting during daytime, as this is the most relevant metric
         if (( current_time_minutes >= start_time_minutes && current_time_minutes <= end_time_minutes ))
         then
-            echo "The current time is between 13:00 and 22:30."
+            echo "The current time is between $TIME_START and $TIME_END."
             echo "Trying to start speedtest..."
-            
+
             # messung durchfuehren
             DISPLAY=:0 xdotool mousemove 531 510
             DISPLAY=:0 xdotool click 1
@@ -73,12 +78,12 @@ do
 
 
             # wait 6 minutes
-            sleep 360
             echo "waiting 6 minutes..."
+            sleep 360
 
-        
+
         else
-            echo "NOT STARTING. The current time is outside the specified range of 13:00 and 22:30."
+            echo "NOT STARTING. The current time is outside the specified range of $TIME_START and $TIME_END."
         fi
 
 
